trigger:
  - main

variables:
  - group: Authentication
  - name: dockerRegistryServiceConnection
    value: "70193de8-17c3-4d45-aed9-7b6d459cb210"
  - name: imageRepository
    value: "terraformimage"
  - name: containerRegistry
    value: "terraformcontainer2023.azurecr.io"
  - name: dockerfilePath
    value: "$(Build.SourcesDirectory)/Dockerfile"
  - name: tag
    value: "$(Build.BuildId)"
  - name: appName
    value: "Azure-test-App-Terraform"
  - name: azureSubscription
    value: "Azure subscription 1 (12d4a125-7d4d-45ad-8101-2ba4e5ce1593)"
  - name: vmImageName
    value: "ubuntu-latest"
  - name: uiSource
    value: "/src"

jobs:
  - job: TerraformDeploy
    displayName: 'Terraform Deployment'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: AzureCLI@2
        displayName: AzureCLI
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: 'ps'
      - script: |
          az --version
          az account show


